version: '3'

services:
  #Service Redis
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  #Interface Grafica do Usuario (GUI)
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8088:8088"