spring:
  application:
    name: ms-learning-attendance
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8083
