spring:
  application:
    name: ms-learning-cad
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms-learning-cad
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  port: 8082

