spring:
  application:
    name: ms-learning-cad
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms-learning-cad
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8082

